# Generated by Django 5.2.5 on 2025-08-14 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the student', primary_key=True, serialize=False)),
                ('student_number', models.CharField(help_text='Unique student registration number', max_length=20, unique=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when student enrolled')),
                ('expected_graduation_date', models.DateField(blank=True, help_text='Expected graduation date', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the student', max_length=1, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', help_text='Current status of the student', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course enrolled by the student', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.course')),
                ('user', models.OneToOneField(help_text='User account associated with this student', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_number'],
            },
        ),
    ]
