# Generated by Django 5.1.1 on 2025-08-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course enrolled by the student (optional initially)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.course'),
        ),
    ]
