# Generated by Django 5.1.1 on 2025-08-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expected_graduation_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
    ]
