# Generated by Django 5.2.5 on 2025-08-14 19:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the course', primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='Name of the course', max_length=255)),
                ('course_code', models.CharField(help_text='Unique course code', max_length=20, unique=True)),
                ('course_duration', models.PositiveIntegerField(help_text='Course duration in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the course', null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='Course prerequisites', null=True)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Number of credits for the course', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_name'],
            },
        ),
    ]
